FROM python:3.8-slim

RUN apt-get clean && apt-get -y update
RUN apt-get -y install build-essential

COPY . /app
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# SCRIPT_NAME is used by app/api/uwsgi.yaml to configure a url prefix for proxy
ARG SCRIPT_NAME=/
ENV SCRIPT_NAME=${SCRIPT_NAME}

EXPOSE 5000
WORKDIR /app
CMD ["uwsgi", "--yaml", "uwsgi.yaml"]